version: '3.8'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/db/data/
    env_file:
      - ./.env

  backend:
    image: awesky/foodgram-backend:1.00
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: awesky/foodgram-frontend:1.00
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    

volumes:
  db_data:
  static_value:
  media_value:
